# https://taskfile.dev

version: "3"

vars:
  DEFAULT_THEME: jsonresume-theme-kendall
  HTML: ./public/index.html

tasks:
  default:
    desc: List all available tasks
    silent: true
    cmds:
      - task --list

  dev:
    desc: Set up the dev environment
    cmds:
      - bun install

  build:
    desc: Build the html
    sources:
      - resume.json
    cmds:
      - bun x resumed render --theme {{.DEFAULT_THEME}} --output {{.HTML}}

  serve:
    desc: Build and serve the resume
    deps:
      - build
    cmds:
      - open {{.HTML}}

  validate:
    desc: Validate the resume JSON
    cmds:
      - bun x resumed validate

  check:
    desc: Spellcheck the CV
    cmds:
      - uv tool run codespell resume.json -L beng,SME

  clean:
    desc: Clean up built artifacts
    cmds:
      - rm -rf exports public
